### ISSUE TITLE
Cached YAML returned after successful edit of JSON

### ISSUE THREAD

**Issue by mboersma** [bspaans/kubefuse#15]
Steps to reproduce:
- mount a `kubefuse` filesystem
- look at the YAML version of an object in `kubefuse`: `cat ~/k8s/default/rc/my-controller.yaml`
- edit an object, e.g.: `vi ~/k8s/default/rc/my-controller/json`, and save a trivial change such as an annotation
- verify that the change was made in Kubernetes: `kubectl get rc my-controller -o json` and inspect the output
- verify that `kubefuse` shows the change: `cat ~/k8s/default/rc/my-controller.json`
- note that the YAML version of the same object is stale: `cat ~/k8s/default/rc/my-controller.yaml`

Caching doesn't seem to be that long-lived, so soon the YAML version will update. But maybe kubefuse should invalidate all the caching at that level after a successful `kubectl edit`?

**Comment by bspaans** [comment]
Thanks for reporting and yes, this seems to be an caching issue. It should invalidate all the yaml, json, describe, etc. keys on write, but doesn't. I'll pick this up.
