### ISSUE TITLE
Note that Python 3 is not supported

### ISSUE THREAD

**Issue by mboersma** [bspaans/kubefuse#16]
I tried to run `kubefuse` with Python 3, but ran into "print without parentheses" errors right away. Python 2 works great. The README should mention this requirement.

**Comment by bspaans** [comment]
Tried adding support for python3 instead. Would you mind giving the branch a go?

https://github.com/opencredo/kubefuse/tree/python3

**Comment by bspaans** [comment]
Just released v0.7 with full Python3 support 🙇
