### ISSUE TITLE
installation requirments

### ISSUE THREAD

**Issue by williamstein** [bspaans/kubefuse#17]
On Ubuntu 16.04 I tried `pip install --user kubefuse` and running it fails with:

```
~> kubefuse kubefuse
Traceback (most recent call last):
  File "/home/salvus/.local/bin/kubefuse", line 7, in <module>
    from kubefuse.kubefuse import main
  File "/home/salvus/.local/lib/python2.7/site-packages/kubefuse/kubefuse.py", line 7, in <module>
    from fuse import FUSE, FuseOSError, Operations, LoggingMixIn
ImportError: cannot import name FUSE
```

due to the built in system-wide fuse module being older (?).

I then did `pip install --user fusepy` and got past the above, then hit a problem with missing yaml.  I then did `pip install --user yaml`, at which point everything worked fine.

(... and this project really awesome!)

**Comment by bspaans** [comment]
Hey thanks for reporting. This should be fixed in HEAD and will be released shortly.
