### ISSUE TITLE
Requirements are not installed & missing pyyaml

### ISSUE THREAD

**Issue by holstvoogd** [bspaans/kubefuse#6]
When installing with pip, fusepy etc do not get installed. After manually installing them I was still missing pyyaml. 
I'm on os x, just did a clean install of python 2.7 from homebrew. Also update to the latest pip version.

**Comment by bspaans** [comment]
Thanks for raising this! Will look into it.

**Comment by bspaans** [comment]
This should be fixed in HEAD and will be released shortly. Thanks for the report!
